/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.AdoptInspectRole;

import Business.Adopt.AdoptRecord;
import Business.EcoSystem.EcoSystem;
import Business.Enterprises.EnterpriseDetails;
import Business.Enterprises.RescueCenterEntDetails;
import Business.Organisation.AdoptionOrganisation;
import Business.UserAccount.UserAccountDetails;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class AdoptInspectorWorkpage extends javax.swing.JPanel {

    /**
     * Creates new form AdoptInspectorWorkpage
     */
    private JPanel container;
    private RescueCenterEntDetails enterprise;
    private AdoptionOrganisation organization;
    private UserAccountDetails userAccount;
    
    public AdoptInspectorWorkpage(JPanel container, EnterpriseDetails enterprise, AdoptionOrganisation adoptionOrg, UserAccountDetails userAccount, EcoSystem business) {
        initComponents();
        this.container = container;
        this.enterprise = (RescueCenterEntDetails)enterprise;
        this.organization = adoptionOrg;
        this.userAccount = userAccount;
        
        populateTable();
    }

    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel)tblApplication.getModel();
        model.setRowCount(0);
        
        for(AdoptRecord ar: organization.getAdoptionRecordDirectory().getAdoptionRecordList()) {
            if(ar.getStatus() == AdoptRecord.SUBMITTED_STATUS) {
                Object[] row = new Object[5];
                row[0] = ar;
                row[1] = ar.getAnimal().getAnimalid();
                row[2] = ar.getAdoptorName().getFirstName() + " " + ar.getAdoptorName().getLastName();
                row[3] = ar.getAdoptorName().getPhoneNumber();
                row[4] = ar.getAdoptorName().getEmail();
                model.addRow(row);
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAdoption = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblApplication = new javax.swing.JTable();
        btnAssign = new javax.swing.JButton();
        btnMy = new javax.swing.JButton();
        btnAnalyse = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAdoption.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblAdoption.setForeground(new java.awt.Color(255, 51, 51));
        lblAdoption.setText("ADOPTION INSPECTOR PANEL");
        add(lblAdoption, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 370, 40));

        tblApplication.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Submitted Date", "Animal ID", "Name", "Phone Number", "Email Address"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblApplication.setSelectionBackground(new java.awt.Color(255, 204, 204));
        tblApplication.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(tblApplication);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 610, 170));

        btnAssign.setBackground(new java.awt.Color(255, 255, 255));
        btnAssign.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnAssign.setForeground(new java.awt.Color(255, 0, 0));
        btnAssign.setText("Assign to Self");
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });
        add(btnAssign, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, 139, 30));

        btnMy.setBackground(new java.awt.Color(255, 255, 255));
        btnMy.setForeground(new java.awt.Color(255, 51, 51));
        btnMy.setText("Inspect");
        btnMy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMyActionPerformed(evt);
            }
        });
        add(btnMy, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, -1, 30));

        btnAnalyse.setBackground(new java.awt.Color(255, 255, 255));
        btnAnalyse.setForeground(new java.awt.Color(255, 51, 51));
        btnAnalyse.setText("Analyze");
        btnAnalyse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalyseActionPerformed(evt);
            }
        });
        add(btnAnalyse, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 95, 30));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 420));

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 630, 190));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblApplication.getSelectedRow();

        if (selectedRow < 0){
            return;
        }

        AdoptRecord ar = (AdoptRecord)tblApplication.getValueAt(selectedRow, 0);
        UserAccountDetails ua = userAccount;
        ar.setInspectorName(ua.getEmployee());
        ar.setStatus(AdoptRecord.PROCESSING_STATUS);
        
        populateTable();
        JOptionPane.showMessageDialog(null, "Work has been assigned to you. Please view it in My Inspections panel.");
    }//GEN-LAST:event_btnAssignActionPerformed

    private void btnMyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMyActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) container.getLayout();
        container.add("MyInspectionJPanel", new MyInspectPanel(container, enterprise, organization, userAccount));
        layout.next(container);
    }//GEN-LAST:event_btnMyActionPerformed

    private void btnAnalyseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalyseActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) container.getLayout();
        container.add("AdoptionOrgAnalyseJPanel", new AdoptOrganalyze(container, enterprise, organization, userAccount));
        layout.next(container);
    }//GEN-LAST:event_btnAnalyseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnalyse;
    private javax.swing.JButton btnAssign;
    private javax.swing.JButton btnMy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAdoption;
    private javax.swing.JTable tblApplication;
    // End of variables declaration//GEN-END:variables
}
