/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.AdoptInspectRole;

import Business.Adopt.AdoptRecord;
import Business.Adopt.AdopterDetail;
import Business.Animals.AnimalDetails;
import Business.Enterprises.RescueCenterEntDetails;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;

/**
 *
 * @author user
 */
public class CheckInspectInfo extends javax.swing.JPanel {

    /**
     * Creates new form CheckInspectInfo
     */
    
    private JPanel container;
    private AdoptRecord ar;
    private RescueCenterEntDetails enterprise;
    
    CheckInspectInfo(JPanel container, RescueCenterEntDetails enterprise, AdoptRecord ar) {
        initComponents();
        this.container = container;
        this.enterprise = enterprise;
        this.ar = ar;
        btnEval.setVisible(false);
        
        populateButton();
        populateValues();
    }
    
    public void populateButton() {
        if(ar.getStatus().equals(AdoptRecord.APPROVED_STATUS) 
                || ar.getStatus().equals(AdoptRecord.REJECTED_STATUS )
                || ar.getStatus().equals(AdoptRecord.INPROGRESS_STATUS)) {
            btnEval.setVisible(false);
        }
        else {
            btnEval.setVisible(true);
        }
    }
    
    public void populateValues() {
        AnimalDetails animal = ar.getAnimal();
        AdopterDetail adopter = ar.getAdoptorName();
        
        lblAnimalId.setText(String.valueOf(animal.getAnimalid()));
        lblType.setText(animal.getAnimaltype().getValue());
        lblColor.setText(animal.getAnimalcolor());
        
        lblSsn.setText(adopter.getSsnnumber());
        lblFirstName.setText(adopter.getFirstName());
        lblLastName.setText(adopter.getLastName());
        lblPhone.setText(adopter.getPhoneNumber());
        lblEmail.setText(adopter.getEmail());
        lblStreet.setText(adopter.getAddress().getStreetName());
        lblCity.setText(adopter.getAddress().getCityName());
        lblState.setText(adopter.getAddress().getStateName());
        
        int size = adopter.getHistoryDirectory().getHistoryList().size();
        if(size == 1) {
            lblHasHistory.setText("No");
        }
        else {
            lblHasHistory.setText("Yes");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAnimalDetails = new javax.swing.JLabel();
        btnPrevious = new javax.swing.JButton();
        lblAnimalType = new javax.swing.JLabel();
        lblColour = new javax.swing.JLabel();
        lblColor = new javax.swing.JLabel();
        lblType = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblAnimalinfo = new javax.swing.JLabel();
        lblAdopterN = new javax.swing.JLabel();
        lblAnimalIdentity = new javax.swing.JLabel();
        lblAnimalId = new javax.swing.JLabel();
        lblSocialsec = new javax.swing.JLabel();
        lblFirstN = new javax.swing.JLabel();
        lblLastN = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        lblFirstName = new javax.swing.JLabel();
        lblSsn = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        LblEmailadd = new javax.swing.JLabel();
        lblPhoneNo = new javax.swing.JLabel();
        lblStreet = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblHasHistory = new javax.swing.JLabel();
        btnEval = new javax.swing.JButton();
        lblCity = new javax.swing.JLabel();
        lblState = new javax.swing.JLabel();

        lblAnimalDetails.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblAnimalDetails.setText("Inspection Details:");

        btnPrevious.setText("Previous");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });

        lblAnimalType.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        lblAnimalType.setText("Type of Animal :");

        lblColour.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        lblColour.setText("Colour:");

        lblColor.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        lblColor.setText("<value>");

        lblType.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        lblType.setText("<value>");

        lblAnimalinfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAnimalinfo.setText("Animal Info");

        lblAdopterN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAdopterN.setText("Adoptor Info");

        lblAnimalIdentity.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        lblAnimalIdentity.setText("Animal ID :");

        lblAnimalId.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        lblAnimalId.setText("<value>");

        lblSocialsec.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        lblSocialsec.setText("Social Security:");

        lblFirstN.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        lblFirstN.setText("First Name:");

        lblLastN.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        lblLastN.setText("Last Name:");

        lblLastName.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        lblLastName.setText("<value>");

        lblFirstName.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        lblFirstName.setText("<value>");

        lblSsn.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        lblSsn.setText("<value>");

        lblAddress.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        lblAddress.setText("Address:");

        LblEmailadd.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        LblEmailadd.setText("Email:");

        lblPhoneNo.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        lblPhoneNo.setText("Phone Number:");

        lblStreet.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        lblStreet.setText("<value>");

        lblEmail.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        lblEmail.setText("<value>");

        lblPhone.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        lblPhone.setText("<value>");

        jLabel13.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jLabel13.setText("Has Adoption History:");

        lblHasHistory.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        lblHasHistory.setText("<value>");

        btnEval.setText("Evaluate");
        btnEval.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEvalActionPerformed(evt);
            }
        });

        lblCity.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        lblCity.setText("<value>");

        lblState.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        lblState.setText("<value>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(lblAnimalIdentity)
                                    .addGap(18, 18, 18)
                                    .addComponent(lblAnimalId, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(33, 33, 33)
                                    .addComponent(lblColour)
                                    .addGap(18, 18, 18)
                                    .addComponent(lblColor, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lblAnimalDetails))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblAnimalType)
                                .addGap(18, 18, 18)
                                .addComponent(lblType, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnPrevious)
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblCity, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblLastN)
                                        .addComponent(lblFirstN))
                                    .addGap(52, 52, 52)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblLastName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblFirstName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblSocialsec)
                                    .addGap(52, 52, 52)
                                    .addComponent(lblSsn, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblAddress)
                                        .addComponent(LblEmailadd)
                                        .addComponent(jLabel13))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(52, 52, 52)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(lblStreet, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lblHasHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(1, 1, 1))))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblPhoneNo)
                                    .addGap(52, 52, 52)
                                    .addComponent(lblPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lblState, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblAdopterN)
                                    .addComponent(btnEval))
                                .addGap(115, 115, 115))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(lblAnimalinfo)))
                .addContainerGap(156, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAnimalDetails)
                .addGap(18, 18, 18)
                .addComponent(lblAnimalinfo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAnimalIdentity)
                    .addComponent(lblAnimalId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblType)
                    .addComponent(lblAnimalType))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblColor)
                    .addComponent(lblColour))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 23, Short.MAX_VALUE)
                        .addComponent(lblAdopterN, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSocialsec)
                            .addComponent(lblSsn))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblFirstN))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLastName)
                            .addComponent(lblLastN))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPhoneNo)
                            .addComponent(lblPhone))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblEmailadd)
                            .addComponent(lblEmail))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStreet)
                            .addComponent(lblAddress))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCity)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblState)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHasHistory)
                            .addComponent(jLabel13)
                            .addComponent(btnPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEval, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        Component[] componentArray = container.getComponents();
        Component component = componentArray[componentArray.length - 1];
        MyInspectPanel mijp = (MyInspectPanel) component;
        mijp.populateTable();
        CardLayout layout = (CardLayout)container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnEvalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEvalActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) container.getLayout();
        container.add("EvaluateJPanel", new EvaluationPage(container, enterprise, ar));
        layout.next(container);
    }//GEN-LAST:event_btnEvalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblEmailadd;
    private javax.swing.JButton btnEval;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAdopterN;
    private javax.swing.JLabel lblAnimalDetails;
    private javax.swing.JLabel lblAnimalId;
    private javax.swing.JLabel lblAnimalIdentity;
    private javax.swing.JLabel lblAnimalType;
    private javax.swing.JLabel lblAnimalinfo;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblColour;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFirstN;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblHasHistory;
    private javax.swing.JLabel lblLastN;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblPhoneNo;
    private javax.swing.JLabel lblSocialsec;
    private javax.swing.JLabel lblSsn;
    private javax.swing.JLabel lblState;
    private javax.swing.JLabel lblStreet;
    private javax.swing.JLabel lblType;
    // End of variables declaration//GEN-END:variables
}
