/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.ShelterRole;

import Business.Animals.AnimalDetails;
import Business.EcoSystem.EcoSystem;
import Business.Enterprises.EnterpriseDetails;
import Business.Enterprises.RescueCenterEntDetails;
import Business.Organisation.ShelterOrganisation;
import Business.ShelterCell.ShelterCellDetails;
import Business.UserAccount.UserAccountDetails;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class ShelterStaffWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ShelterStaffWorkAreaJPanel
     */
    
    private JPanel container;
    private RescueCenterEntDetails enterprise;
    private ShelterOrganisation organization;
    private UserAccountDetails userAccount;
    
    public ShelterStaffWorkAreaJPanel(JPanel container, EnterpriseDetails enterprise, ShelterOrganisation shelterOrg, UserAccountDetails userAccount, EcoSystem business) {
        initComponents();
        this.container = container;
        this.enterprise = (RescueCenterEntDetails)enterprise;
        this.organization = shelterOrg;
        this.userAccount = userAccount;
        
        populateTable();
    }

    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel)tblShelter.getModel();
        model.setRowCount(0);
        
        for(ShelterCellDetails sc: enterprise.getShelterCellDirectory().getShelterCellList()){
            if(sc.getShelterstatus() == ShelterCellDetails.OCCUPIED_STATUS) {
                Object[] row = new Object[5];
                row[0] = sc;
                row[1] = sc.getShelterlocation();
                row[2] = sc.getAnimal().getAnimaltype();
                row[3] = sc.getAnimal().getAnimalcolor();
                if(sc.getAnimal().getAnimalstatus() == AnimalDetails.ADOPTED_STATUS) {
                    row[4] = "Yes";
                }
                else {
                    row[4] = "No";
                }
                model.addRow(row);
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblshelterstaffworkarea = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblShelter = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblshelterstaffworkarea.setBackground(new java.awt.Color(255, 255, 255));
        lblshelterstaffworkarea.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblshelterstaffworkarea.setForeground(new java.awt.Color(255, 51, 51));
        lblshelterstaffworkarea.setText("SHELTER STAFF WORKSPACE");
        add(lblshelterstaffworkarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        tblShelter.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Shelter", "Location", "Animal Type", "Color", "Adopted or Not"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblShelter.setSelectionBackground(new java.awt.Color(255, 204, 204));
        tblShelter.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(tblShelter);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 550, 300));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblshelterstaffworkarea;
    private javax.swing.JTable tblShelter;
    // End of variables declaration//GEN-END:variables
}
