/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.EntAdminRole;

import Business.Enterprises.EnterpriseDetails;
import javax.swing.JPanel;
import java.awt.CardLayout;

/**
 *
 * @author Administrator
 */
public class AdminWorkAreaJPanel extends javax.swing.JPanel {

   JPanel userProcessContainer;
    EnterpriseDetails enterprise;
    /** Creates new form AdminWorkAreaJPanel */
    public AdminWorkAreaJPanel(JPanel userProcessContainer, EnterpriseDetails enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        lblValue.setText(enterprise.getOrgname());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEnterprise = new javax.swing.JLabel();
        btnUser = new javax.swing.JButton();
        btnManageEmployee = new javax.swing.JButton();
        btnManage = new javax.swing.JButton();
        lblEnter = new javax.swing.JLabel();
        lblValue = new javax.swing.JLabel();
        btnRoom = new javax.swing.JButton();
        btnMedicine = new javax.swing.JButton();
        btnCage = new javax.swing.JButton();
        btnShelter = new javax.swing.JButton();
        btnAnalyse = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEnterprise.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblEnterprise.setForeground(new java.awt.Color(255, 41, 41));
        lblEnterprise.setText("Enterprise Admin Work Area");
        add(lblEnterprise, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        btnUser.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnUser.setText("Manage User");
        btnUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserActionPerformed(evt);
            }
        });
        add(btnUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 171, 50));

        btnManageEmployee.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnManageEmployee.setText("Manage Employee");
        btnManageEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageEmployeeActionPerformed(evt);
            }
        });
        add(btnManageEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 171, 50));

        btnManage.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnManage.setText("Manage Organization");
        btnManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageActionPerformed(evt);
            }
        });
        add(btnManage, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 171, 50));

        lblEnter.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblEnter.setText("Enterprise :");
        add(lblEnter, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 120, 30));

        lblValue.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        lblValue.setText("<value>");
        add(lblValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 130, -1));

        btnRoom.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnRoom.setText("Manage Room");
        btnRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRoomActionPerformed(evt);
            }
        });
        add(btnRoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 171, 50));

        btnMedicine.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnMedicine.setText("Manage Medicine");
        btnMedicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedicineActionPerformed(evt);
            }
        });
        add(btnMedicine, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 268, 171, 50));

        btnCage.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnCage.setText("Manage Cage");
        btnCage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCageActionPerformed(evt);
            }
        });
        add(btnCage, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, 171, 50));

        btnShelter.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnShelter.setText("Manage Shelter");
        btnShelter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShelterActionPerformed(evt);
            }
        });
        add(btnShelter, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 349, 171, 50));

        btnAnalyse.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        btnAnalyse.setText("Analysis");
        btnAnalyse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalyseActionPerformed(evt);
            }
        });
        add(btnAnalyse, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 349, 171, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void btnUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserActionPerformed
        // TODO add your handling code here:
        ManageUserAccountJPanel muajp = new ManageUserAccountJPanel(userProcessContainer, enterprise);
        userProcessContainer.add("ManageUserAccountJPanel", muajp);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnUserActionPerformed

    private void btnManageEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageEmployeeActionPerformed

        ManageEmployeeJPanel manageEmployeeJPanel = new ManageEmployeeJPanel(userProcessContainer, enterprise.getOrganisationDirectory());
        userProcessContainer.add("manageEmployeeJPanel", manageEmployeeJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_btnManageEmployeeActionPerformed

    private void btnManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageActionPerformed

        ManageOrganizationJPanel manageOrganizationJPanel = new ManageOrganizationJPanel(userProcessContainer, enterprise.getOrganisationDirectory());
        userProcessContainer.add("manageOrganizationJPanel", manageOrganizationJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageActionPerformed

    private void btnRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRoomActionPerformed
        // TODO add your handling code here:
        ManageRoomsJPanel manageRoomsJPanel = new ManageRoomsJPanel(userProcessContainer, enterprise);
        userProcessContainer.add("manageRoomsJPanel", manageRoomsJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnRoomActionPerformed

    private void btnMedicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedicineActionPerformed
        // TODO add your handling code here:
        ManageMedicineJPanel manageMedicineJPanel = new ManageMedicineJPanel(userProcessContainer, enterprise);
        userProcessContainer.add("manageMedicineJPanel", manageMedicineJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnMedicineActionPerformed

    private void btnCageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCageActionPerformed
        // TODO add your handling code here:
        ManageCageJPanel manageCageJPanel = new ManageCageJPanel(userProcessContainer, enterprise);
        userProcessContainer.add("manageCageJPanel", manageCageJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnCageActionPerformed

    private void btnShelterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShelterActionPerformed
        // TODO add your handling code here:
        ManageShelterJPanel manageShelterJPanel = new ManageShelterJPanel(userProcessContainer, enterprise);
        userProcessContainer.add("manageShelterJPanel", manageShelterJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnShelterActionPerformed

    private void btnAnalyseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalyseActionPerformed
        // TODO add your handling code here:
        EnterpriseAnalyseJPanel enterpriseAnalyseJPanel = new EnterpriseAnalyseJPanel(userProcessContainer, enterprise);
        userProcessContainer.add("enterpriseAnalyseJPanel", enterpriseAnalyseJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnAnalyseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnalyse;
    private javax.swing.JButton btnCage;
    private javax.swing.JButton btnManage;
    private javax.swing.JButton btnManageEmployee;
    private javax.swing.JButton btnMedicine;
    private javax.swing.JButton btnRoom;
    private javax.swing.JButton btnShelter;
    private javax.swing.JButton btnUser;
    private javax.swing.JLabel lblEnter;
    private javax.swing.JLabel lblEnterprise;
    private javax.swing.JLabel lblValue;
    // End of variables declaration//GEN-END:variables
}
