/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.AdoptorRole;

import Business.Adopt.AdoptHistory;
import Business.EcoSystem.EcoSystem;
import Business.Enterprises.EnterpriseDetails;
import Business.Enterprises.RescueCenterEntDetails;
import Business.Network.NetworkDetails;
import Business.Deliver.DeliveryHistoryDetails;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author user
 */
public class SeeDeliverydetailspage extends javax.swing.JPanel {

    /**
     * Creates new form SeeDeliverydetailspage
     */
    
    private JPanel container;
    private EcoSystem business;
    private AdoptHistory history;
    private DeliveryHistoryDetails dh;
    
    SeeDeliverydetailspage(JPanel container, EcoSystem business, AdoptHistory history) {
        initComponents();
        this.container = container;
        this.business = business;
        this.history = history;
        for(NetworkDetails n: business.getNetworkList()) {
            for(EnterpriseDetails e: n.getEnterpriseDirectory().getEnterpriseList()) {
                if(e instanceof RescueCenterEntDetails) {
                    for(DeliveryHistoryDetails dh: ((RescueCenterEntDetails) e).getDeliveryHistoryDirectory().getDeliveryHistoryList()) {
                        if(dh.getAnimal() == history.getAnimalname()) {
                            this.dh = dh;
                        }
                    }
                }
            }
        }
        btnRcv.setVisible(false);
        if(dh.getStatus().equals(DeliveryHistoryDetails.ASSIGNED_STATUS)) {
            btnRcv.setVisible(true);
        }
        
        populateValues();
    }

    public void populateValues() {
        if(dh.getDate() == null) {
            lblDate.setText("Waiting...");
        }
        else {
            String dateFormat = dh.getDate().getMonth()
                                + "/" + dh.getDate().getDate()
                                + "/" + dh.getDate().getYear();
            lblDate.setText(dateFormat);
        }
        
        if(dh.getCourierdetail() == null) {
            lblId.setText("Not Assigned");
        }
        else {
            lblId.setText(String.valueOf(dh.getCourierdetail().getEmpid()));
        }
        
        if(dh.getStatus().equals(DeliveryHistoryDetails.WAITING_STATUS)) {
            lblStatus.setText("Waiting...");
        }
        else if(dh.getStatus().equals(DeliveryHistoryDetails.ASSIGNED_STATUS)) {
            lblStatus.setText("In Progress");
        }
        else if(dh.getStatus().equals(DeliveryHistoryDetails.RECEIVED_STATUS)) {
            lblStatus.setText("Arrived");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPrevious = new javax.swing.JButton();
        lblDeliveryInfo = new javax.swing.JLabel();
        lblDeliveryDt = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        lblEmployee = new javax.swing.JLabel();
        lblStats = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        btnRcv = new javax.swing.JButton();

        btnPrevious.setText("Previous");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });

        lblDeliveryInfo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblDeliveryInfo.setText("Delivery Information");

        lblDeliveryDt.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        lblDeliveryDt.setText("Delivery Date:");

        lblDate.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        lblDate.setText("<value>");

        lblId.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        lblId.setText("<value>");

        lblEmployee.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        lblEmployee.setText("Employee ID:");

        lblStats.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        lblStats.setText("Status:");

        lblStatus.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        lblStatus.setText("<value>");

        btnRcv.setText("Receive");
        btnRcv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRcvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(163, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblDeliveryDt)
                                .addComponent(lblStats)
                                .addComponent(lblEmployee))
                            .addGap(52, 52, 52)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblId, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(89, 89, 89)
                            .addComponent(btnRcv, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblDeliveryInfo))
                .addGap(164, 164, 164))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDeliveryInfo)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDeliveryDt)
                    .addComponent(lblDate))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStats)
                    .addComponent(lblStatus))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmployee)
                    .addComponent(lblId))
                .addGap(31, 31, 31)
                .addComponent(btnRcv, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(btnPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        Component[] componentArray = container.getComponents();
        Component component = componentArray[componentArray.length - 1];
        SeeHistoryPage shdjp = (SeeHistoryPage) component;
        shdjp.populateValues();
        CardLayout layout = (CardLayout)container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnRcvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRcvActionPerformed
        // TODO add your handling code here:
        dh.setStatus(DeliveryHistoryDetails.RECEIVED_STATUS);
        JOptionPane.showMessageDialog(null, "Thank you for your feedback!");
        btnRcv.setVisible(false);
    }//GEN-LAST:event_btnRcvActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton btnRcv;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDeliveryDt;
    private javax.swing.JLabel lblDeliveryInfo;
    private javax.swing.JLabel lblEmployee;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblStats;
    private javax.swing.JLabel lblStatus;
    // End of variables declaration//GEN-END:variables
}
