/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Pharmacist;

import Business.Enterprises.RescueCenterEntDetails;
import Business.Medicines.MedicineDetails;
import Business.Organisation.OrganisationMain;
import Business.Organisation.PharmacyOrganisation;
import Business.Organisation.VeterinarianOrganisation;
import Business.Treatment.TreatmentRecordDetails;
import Business.WorkQueue.PharmacyWre;
import Business.WorkQueue.PharmacyUnitWre;
import Business.WorkQueue.AllWorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Neha
 */
public class MedicineAnalyse extends javax.swing.JPanel {

    /**
     * Creates new form MedicineAnalyse
     */
    
    private JPanel container;
    private RescueCenterEntDetails enterprise;
    private PharmacyOrganisation organization;
    
    public MedicineAnalyse(JPanel container, RescueCenterEntDetails enterprise,PharmacyOrganisation organization) {
        initComponents();
        this.container = container;
        this.enterprise = (RescueCenterEntDetails)enterprise;
        this.organization = organization;
        
        populateTable();
    }
    
    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel)tblMedicine.getModel();
        model.setRowCount(0);
        for(MedicineDetails m: enterprise.getMedicineDirectory().getMedicineList()) {
            int count = 0;
            Object[] row = new Object[2];
            row[0] = m;
            for(AllWorkRequest wr: organization.getWorkQueue().getWorkRequestList()) {
                if(wr instanceof PharmacyWre) {
                    if(((PharmacyWre) wr).getMedicineList() != null) {
                        for(PharmacyUnitWre ru: ((PharmacyWre) wr).getMedicineList()) {
                            if(ru.getMedicine() == m) {
                                count += ru.getQuantity();
                            }
                        }
                    }
                }
            }
            row[1] = count;
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPrevious = new javax.swing.JButton();
        lblMedicineAna = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMedicine = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPrevious.setText("Previous");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });
        add(btnPrevious, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 81, 32));

        lblMedicineAna.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblMedicineAna.setForeground(new java.awt.Color(255, 41, 41));
        lblMedicineAna.setText("Medicine Analysis");
        add(lblMedicineAna, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 14, -1, -1));

        tblMedicine.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Medicine", "Amount Used"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblMedicine);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 419, 240));
    }// </editor-fold>//GEN-END:initComponents

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_btnPreviousActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrevious;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMedicineAna;
    private javax.swing.JTable tblMedicine;
    // End of variables declaration//GEN-END:variables
}
