/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Receptionist;

import Business.Animals.AnimalDetails;
import Business.Enterprises.EnterpriseDetails;
import Business.Enterprises.RescueCenterEntDetails;
import Business.Network.NetworkDetails;
import Business.Organisation.CenterRegistrationOrganisation;
import Business.Organisation.VeterinarianOrganisation;
import Business.RescueRecord.RescueRecordDetails;
import Business.Place.PlaceDetails;
import Business.UserAccount.UserAccountDetails;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Neha
 */
public class ReceptionistPanel extends javax.swing.JPanel {

    /**
     * Creates new form ReceptionistPanel
     */
    private JPanel container;
    private RescueCenterEntDetails enterprise;
    private CenterRegistrationOrganisation organization;
    private UserAccountDetails userAccount;
    
    public ReceptionistPanel(JPanel container, RescueCenterEntDetails enterprise, CenterRegistrationOrganisation organization, UserAccountDetails userAccount) {
        initComponents();
        this.container = container;
        this.enterprise = enterprise;
        this.organization = organization;
        this.userAccount = userAccount;
        
        populateAnimalTable();
    }
    
   
    
    public void populateAnimalTable() {
        DefaultTableModel model = (DefaultTableModel) tblAnimal.getModel();

        model.setRowCount(0);
        for (RescueRecordDetails r : enterprise.getRecordDirectory().getRescueRecordList()) {
            Object[] row = new Object[4];
            row[0] = r;
            row[1] = r.getRescuedanimal().getAnimalid();
            row[2] = r.getRescuedanimal().getAnimaltype();
            if(r.getRescueroom() == null) {
                row[3] = "Waiting...";
            }
            else {
                row[3] = r.getRescueroom().getRoomno();
            } 
            
            model.addRow(row);
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblReceptionist = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAnimal = new javax.swing.JTable();
        btnCreate = new javax.swing.JButton();

        lblReceptionist.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblReceptionist.setForeground(new java.awt.Color(255, 41, 41));
        lblReceptionist.setText("Center Receptionist Work Space");

        tblAnimal.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Work space", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 15), new java.awt.Color(255, 41, 41))); // NOI18N
        tblAnimal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date(MM/DD/YYYY)", "Animal ID", "Animal Type", "Room"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblAnimal);
        if (tblAnimal.getColumnModel().getColumnCount() > 0) {
            tblAnimal.getColumnModel().getColumn(0).setResizable(false);
            tblAnimal.getColumnModel().getColumn(1).setResizable(false);
            tblAnimal.getColumnModel().getColumn(2).setResizable(false);
            tblAnimal.getColumnModel().getColumn(3).setResizable(false);
        }

        btnCreate.setText("Create New");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(lblReceptionist))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 69, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblReceptionist)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) container.getLayout();
        container.add("RequestLabTestJPanel", new RegisterAnimalPanel(container, enterprise, userAccount));
        layout.next(container);
    }//GEN-LAST:event_btnCreateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblReceptionist;
    private javax.swing.JTable tblAnimal;
    // End of variables declaration//GEN-END:variables
}
