/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.VetAssistRole;

import Business.Animals.AnimalDetails;
import Business.Cages.CageDetail;
import Business.Date.Date;
import Business.EcoSystem.EcoSystem;
import Business.Enterprises.EnterpriseDetails;
import Business.Enterprises.RescueCenterEntDetails;
import Business.Organisation.CageOrganisation;
import static Business.Organisation.OrganisationMain.Type.Cage;
import Business.Treatment.TreatmentRecordDetailsDirectory;
import Business.UserAccount.UserAccountDetails;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class VeteAssistantWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form VeteAssistantWorkAreaJPanel
     */
    
    private JPanel container;
    private RescueCenterEntDetails enterprise;
    private CageOrganisation organization;
    private UserAccountDetails userAccount;
    
    public VeteAssistantWorkAreaJPanel(JPanel container, EnterpriseDetails enterprise, CageOrganisation cageOrg, UserAccountDetails userAccount) {
        initComponents();
        this.container = container;
        this.enterprise = (RescueCenterEntDetails)enterprise;
        this.organization = cageOrg;
        this.userAccount = userAccount;
        
        populateTable();
    }
    
    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel)tblCage.getModel();
        model.setRowCount(0);
        
        for(CageDetail c: enterprise.getCageCellDirectory().getCageCellList()){
            if(c.getCagestatus() == CageDetail.OCCUPIED_STATUS 
                    && c.getAnimal().getAnimalstatus() == AnimalDetails.UNREADY_STATUS) {
                TreatmentRecordDetailsDirectory t = c.getAnimal().getTreatmentDirectory();
                int size = t.getTreatmentRecordList().size();
                if(t.getTreatmentRecordList().get(size-1).isReviewed() == true) {
                    break;
                }
                
                Object[] row = new Object[5];
                row[0] = c;
                row[1] = c.getCagelocation();
                row[2] = c.getAnimal().getAnimaltype();
                row[3] = c.getAnimal().getAnimalcolor();
                
                Date d = t.getTreatmentRecordList().get(size-1).getDate();
                row[4] = c.getAnimal().getNextcheck().getMonth()
                        + "/" + c.getAnimal().getNextcheck().getDate()
                        + "/" + c.getAnimal().getNextcheck().getYear();
                model.addRow(row);
            }
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCage = new javax.swing.JTable();
        btnAssign = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Veterinarian Assistant WorkArea");

        tblCage.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cage", "Location", "Animal Type", "Color", "Review Date(MM/DD/YYYY)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCage);

        btnAssign.setText("Assign To Me");
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAssign)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(29, 29, 29)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAssign, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblCage.getSelectedRow();
        
        if (selectedRow < 0){
            return;
        }
        
        CageDetail c = (CageDetail)tblCage.getValueAt(selectedRow, 0);
        
        CardLayout layout = (CardLayout) container.getLayout();
        container.add("ReviewAnimalJPanel", new ReviewAnimalJPanel(container, enterprise, c));
        layout.next(container);
        
    }//GEN-LAST:event_btnAssignActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssign;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCage;
    // End of variables declaration//GEN-END:variables
}
